# Generated by Django 5.1.3 on 2024-12-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_given_names', models.CharField(max_length=255, verbose_name='Official Given Names')),
                ('surnames', models.CharField(max_length=255, verbose_name='Surnames')),
                ('address', models.TextField(verbose_name='Address')),
                ('zip_code_and_place', models.CharField(max_length=255, verbose_name='ZIP Code and Place')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('telephone_number', models.CharField(max_length=20, verbose_name='Telephone Number')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('place_of_birth', models.CharField(max_length=255, verbose_name='Place of Birth')),
                ('bsn', models.CharField(max_length=20, verbose_name='BSN')),
                ('iban_number', models.CharField(max_length=34, verbose_name='IBAN Number')),
                ('nationality', models.CharField(max_length=100, verbose_name='Nationality')),
                ('number_id', models.CharField(max_length=50, verbose_name='Number ID')),
                ('id_date_of_expiry', models.DateField(verbose_name='ID Date of Expiry')),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Registered Partnership', 'Registered Partnership'), ('Divorced', 'Divorced'), ('Living Together Without Contract', 'Living Together Without Contract')], max_length=50, verbose_name='Marital Status')),
                ('name_spouse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Spouse (if married)')),
                ('travel_to_work', models.CharField(choices=[('Car', 'Car'), ('Public Transport', 'Public Transport'), ('Bicycle', 'Bicycle')], max_length=20, verbose_name='How Do You Travel to Work?')),
                ('available_from_date', models.DateField(verbose_name='Available From What Date')),
                ('shirt_size', models.CharField(blank=True, max_length=10, null=True, verbose_name='Shirt Size')),
                ('trouser_size', models.CharField(blank=True, max_length=10, null=True, verbose_name='Trousers/Pants Size')),
                ('id_front', models.ImageField(blank=True, null=True, upload_to='documents/id/', verbose_name='ID Front')),
                ('id_back', models.ImageField(blank=True, null=True, upload_to='documents/id/', verbose_name='ID Back')),
                ('bank_card', models.ImageField(blank=True, null=True, upload_to='documents/bank_card/', verbose_name='Bank Card')),
                ('health_insurance_front', models.ImageField(blank=True, null=True, upload_to='documents/health_insurance/', verbose_name='Health Insurance Card Front')),
                ('health_insurance_back', models.ImageField(blank=True, null=True, upload_to='documents/health_insurance/', verbose_name='Health Insurance Card Back')),
                ('work_permit', models.FileField(blank=True, null=True, upload_to='documents/work_permit/', verbose_name='Work Permit')),
            ],
        ),
    ]
